### ISSUE TITLE
Values are not correct

### ISSUE THREAD

**Issue by querwin** [Centreon-Widgets/centreon-widget-tactical-overview#2]
Right now, I have 146 hosts et 1408 services on my Centreon.

The widget shows me about 20 * more of elements (3177 hosts).

**Comment by Moujimouja** [comment]
Same 

![image](https://cloud.githubusercontent.com/assets/6620287/15649228/54c775d6-2670-11e6-91ce-0c39bad6a8aa.png)

**Comment by bmareau** [comment]
Same problem.
With a admin user : 9 hosts down
With a simple user : 213 hosts down
